# Generated by Django 5.2.12 on 2026-05-02 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olxapp', '0004_bookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, default='+998', max_length=15, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='advertisement',
            name='advertisters',
            field=models.ManyToManyField(related_name='advertister', to='olxapp.advertister'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='olxapp.region'),
        ),
    ]
