# Generated by Django 5.2.12 on 2026-05-07 10:19

import django.db.models.deletion
import olxapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olxapp', '0005_advertister_region_advertisement_advertisters_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ('title', '-create_at'), 'verbose_name': 'Elon', 'verbose_name_plural': 'Elonlar'},
        ),
        migrations.AlterModelOptions(
            name='advertister',
            options={'ordering': ('name',), 'verbose_name': 'Elon Joylovchi', 'verbose_name_plural': 'Elon Joylovchilar'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Bolim', 'verbose_name_plural': 'Bolimlar'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Izox', 'verbose_name_plural': 'Izoxlar'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ('region_name',), 'verbose_name': 'Joylashuv', 'verbose_name_plural': 'Joylashuvlar'},
        ),
        migrations.AddField(
            model_name='advertisement',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/', verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='advertisters',
            field=models.ManyToManyField(related_name='advertister', to='olxapp.advertister', verbose_name='Elon joylovchi'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olxapp.category', verbose_name='Bolim'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='description',
            field=models.TextField(verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='olxapp.region', verbose_name='Joylashuv'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='advertister',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ismi'),
        ),
        migrations.AlterField(
            model_name='advertister',
            name='phone_number',
            field=models.CharField(blank=True, default='+998', max_length=15, null=True, unique=True, verbose_name='Telefon raqam'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(default='', max_length=40, validators=[olxapp.models.validate_description], verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Bolim nomi'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=100, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Joylashuv nomi'),
        ),
    ]
